export const QUARTIERS_CONAKRY = [
    // Autoroute
    'Km 36',
    'Kountia',
    'Lansanayah Barrage',
    'Dabompa',
    'Tombolia',
    'Enta',
    'Kissosso',
    'Sangoyah',
    'Matoto',
    'Yimbayah',
    'Aeroport',
    'Gbessia',
    'Dabondy',
    'Bonfi',
    'Matam',
    'Kenien',
    'Madina',
    'Donka',
    'Cameroun',
    'Pont 8 Novembre',
    'Kaloum',
    'En Ville',
    'Centre Ville',

    // Route du Prince
    'Cimenterie',
    'T8',
    'Sonfonia',
    'T7',
    'T6',
    'T5',
    'Wanindara',
    'Enco5',
    'Cosa',
    'Bambeto',
    'Hamdallaye',
    'Miniere',
    'Dixinn',

    // Corniche
    'Yattaya',
    'Kobayah',
    'Lambanyi',
    'Nongo',
    'Kaporo',
    'Kipe',
    'Ratoma',
    'Taouyah',
];