# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Clando
spring.datasource.username=postgres
spring.datasource.password=&Mariamediak5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**

# Port
server.port=8080

spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**

server.error.include-message=always
server.error.include-binding-errors=always
# JWT

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=604800000