spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Clando}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:&Mariamediak5}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=604800000
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.mvc.static-path-pattern=/**
spring.jpa.open-in-view=false
djomy.client.id=djomy-client-1781741064647-a14e
djomy.client.secret=s3cr3t-6TCU91Kl88T5aO-a3gZXLlRw3ReMCBAG
djomy.base.url=https://sandbox-api.djomy.africa